// ──────────────────────────────────────────────────────────────
// XIOM World Model — Receipt Query Helpers
// Cryptographic hash-chained receipts for every agent action.
// ──────────────────────────────────────────────────────────────
import { createHash } from 'crypto';
import type { Neo4jConnectionManager } from '../connection.js';
import type { ReceiptNode } from '../types/nodes.js';
import { WorldModelDomain } from '../types/domains.js';

type CreateReceiptData = Omit<
  ReceiptNode,
  | 'id'
  | 'nodeType'
  | 'receiptNumber'
  | 'createdAt'
  | 'updatedAt'
  | 'version'
  | 'isDeleted'
  | 'prevHash'
  | 'hash'
>;

// ─── Hash chain helpers ───────────────────────────────────────

/** The genesis hash for a chain with no prior entries */
const GENESIS_HASH = '0'.repeat(64);

async function getLatestReceiptHash(
  conn: Neo4jConnectionManager,
  humanId: string
): Promise<string> {
  const result = await conn.queryOne<{ hash: string }>(
    `MATCH (:Human {id: $humanId})-[:HAS_GOAL|GENERATED_RECEIPT*1..3]->(r:Receipt)
     RETURN r.hash AS hash
     ORDER BY r.createdAt DESC
     LIMIT 1`,
    { humanId }
  );
  return result?.hash ?? GENESIS_HASH;
}

function computeReceiptHash(
  prevHash: string,
  timestamp: string,
  intent: string,
  action: string,
  result: string
): string {
  return createHash('sha256')
    .update(`${prevHash}${timestamp}${intent}${action}${result}`)
    .digest('hex');
}

async function nextReceiptNumber(
  conn: Neo4jConnectionManager,
  humanId: string
): Promise<string> {
  const today = new Date().toISOString().slice(0, 10); // YYYY-MM-DD
  const result = await conn.queryOne<{ count: number }>(
    `MATCH (:Human {id: $humanId})-[:HAS_GOAL|GENERATED_RECEIPT*1..3]->(r:Receipt)
     WHERE r.receiptNumber STARTS WITH $prefix
     RETURN count(r) AS count`,
    { humanId, prefix: today }
  );
  const seq = String((result?.count ?? 0) + 1).padStart(4, '0');
  return `${today}-${seq}`;
}

// ─── Public API ───────────────────────────────────────────────

/**
 * Issue a new Receipt and append it to this human's hash chain.
 * MUST be called inside a write transaction for atomicity.
 */
export async function createReceipt(
  conn: Neo4jConnectionManager,
  humanId: string,
  data: CreateReceiptData
): Promise<ReceiptNode> {
  const id = crypto.randomUUID();
  const now = new Date();
  const timestamp = now.toISOString();

  const prevHash   = await getLatestReceiptHash(conn, humanId);
  const hash       = computeReceiptHash(prevHash, timestamp, data.intent, data.action, data.result);
  const receiptNumber = await nextReceiptNumber(conn, humanId);

  const params: Record<string, unknown> = {
    humanId,
    id,
    receiptNumber,
    intent:           data.intent,
    context:          data.context,
    policy:           data.policy,
    action:           data.action,
    result:           data.result,
    isApproved:       data.isApproved,
    rollbackAvailable:data.rollbackAvailable,
    prevHash,
    hash,
    domain:           data.domain,
    confidence:       data.confidence,
    now:              timestamp,
  };

  if (data.source !== undefined) params['source'] = data.source;

  await conn.query(
    `CREATE (r:Receipt {
       id:               $id,
       nodeType:         'Receipt',
       receiptNumber:    $receiptNumber,
       intent:           $intent,
       context:          $context,
       policy:           $policy,
       action:           $action,
       result:           $result,
       isApproved:       $isApproved,
       rollbackAvailable:$rollbackAvailable,
       prevHash:         $prevHash,
       hash:             $hash,
       domain:           $domain,
       confidence:       $confidence,
       version:          1,
       isDeleted:        false,
       createdAt:        $now,
       updatedAt:        $now
     })`,
    params
  );

  return {
    id,
    nodeType:         'Receipt',
    receiptNumber,
    intent:           data.intent,
    context:          data.context,
    policy:           data.policy,
    action:           data.action,
    result:           data.result,
    isApproved:       data.isApproved,
    rollbackAvailable:data.rollbackAvailable,
    prevHash,
    hash,
    domain:           data.domain,
    confidence:       data.confidence,
    version:          1,
    isDeleted:        false,
    createdAt:        now,
    updatedAt:        now,
    ...(data.source !== undefined ? { source: data.source } : {}),
  };
}

/**
 * Get all receipts generated by a specific action.
 */
export async function getReceiptsForAction(
  conn: Neo4jConnectionManager,
  actionId: string
): Promise<ReceiptNode[]> {
  const rows = await conn.queryMany<{ receipt: Record<string, unknown> }>(
    `MATCH (:Action {id: $actionId})-[:GENERATED_RECEIPT]->(r:Receipt {isDeleted: false})
     RETURN r { .* } AS receipt
     ORDER BY r.createdAt DESC`,
    { actionId }
  );
  return rows.map((r) => mapReceipt(r.receipt));
}

/**
 * Traverse the receipt hash chain for a human and verify every link.
 * Returns { valid: true } if the entire chain is intact.
 * Returns { valid: false, brokenAt: receiptId } at the first failure.
 */
export async function verifyReceiptChain(
  conn: Neo4jConnectionManager,
  humanId: string
): Promise<{ valid: boolean; brokenAt?: string }> {
  const receipts = await conn.queryMany<{
    id: string;
    prevHash: string;
    hash: string;
    intent: string;
    action: string;
    result: string;
    createdAt: string;
  }>(
    `MATCH (:Human {id: $humanId})-[:HAS_GOAL|GENERATED_RECEIPT*1..3]->(r:Receipt)
     RETURN r.id        AS id,
            r.prevHash  AS prevHash,
            r.hash      AS hash,
            r.intent    AS intent,
            r.action    AS action,
            r.result    AS result,
            r.createdAt AS createdAt
     ORDER BY r.createdAt ASC`,
    { humanId }
  );

  let expectedPrev = GENESIS_HASH;

  for (const r of receipts) {
    if (r.prevHash !== expectedPrev) {
      return { valid: false, brokenAt: r.id };
    }
    const expected = computeReceiptHash(r.prevHash, r.createdAt, r.intent, r.action, r.result);
    if (r.hash !== expected) {
      return { valid: false, brokenAt: r.id };
    }
    expectedPrev = r.hash;
  }

  return { valid: true };
}

// ─── Mapper ───────────────────────────────────────────────────

function mapReceipt(raw: Record<string, unknown>): ReceiptNode {
  return {
    id:               String(raw['id'] ?? ''),
    nodeType:         'Receipt',
    receiptNumber:    String(raw['receiptNumber'] ?? ''),
    intent:           String(raw['intent'] ?? ''),
    context:          String(raw['context'] ?? ''),
    policy:           String(raw['policy'] ?? ''),
    action:           String(raw['action'] ?? ''),
    result:           String(raw['result'] ?? ''),
    isApproved:       Boolean(raw['isApproved'] ?? false),
    rollbackAvailable:Boolean(raw['rollbackAvailable'] ?? false),
    prevHash:         String(raw['prevHash'] ?? GENESIS_HASH),
    hash:             String(raw['hash'] ?? ''),
    domain:           (raw['domain'] as WorldModelDomain) ?? WorldModelDomain.TRACK,
    confidence:       Number(raw['confidence'] ?? 1),
    version:          Number(raw['version'] ?? 1),
    isDeleted:        Boolean(raw['isDeleted'] ?? false),
    createdAt:        raw['createdAt'] ? new Date(String(raw['createdAt'])) : new Date(),
    updatedAt:        raw['updatedAt'] ? new Date(String(raw['updatedAt'])) : new Date(),
    ...(raw['source'] !== undefined ? { source: String(raw['source']) } : {}),
  };
}
